[global]
developmentMode = false

[server]
headless = false
enableStaticServing = true
runOnSave = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[logger]
level = "error"

[client]
showErrorDetails = true